name: image_editor
description: Edit your image data and output to file/memory on Android and iOS.
version: 1.0.2
homepage: https://github.com/fluttercandies/flutter_image_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: top.kikt.flutter_image_editor
        pluginClass: FlutterImageEditorPlugin
      ios:
        pluginClass: FlutterImageEditorPlugin
      macos:
        pluginClass: FlutterImageEditorPlugin
      