name: flutter_image_editor_example
description: Demonstrates how to use the flutter_image_editor plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_editor:
    path: ..

  extended_image: ^9.0.7
  image_picker: ^0.8.5+3
  oktoast: ^3.1.5
  path_provider: ^2.0.0
  image_size_getter: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
